<nav class="navbar navbar-expand-md navbar-dark fixed-top" id="banner">
    <div class="container">
        <!-- Brand -->
        <a class="navbar-brand" href="<?= $this->_router->get(['controller' => 'home']) ?>"><span>Vice</span> Manager Service</a>

        <!-- Toggler/collapsibe Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav ml-auto">
                <?php foreach ($this->_userMenu[(empty($this->user) ? 'guest' : 'logged')] as $menuItem) : ?>
                    <?php if (!empty($menuItem['children'])) : ?>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                <?= $menuItem['title'] ?>
                            </a>
                            <div class="dropdown-menu">
                                <?php foreach ($menuItem['children'] as $childItem) : ?>
                                    <a class="dropdown-item" href="<?= $this->_router->get($childItem['url']) ?>">
                                        <?= $childItem['title'] ?>
                                    </a>
                                <?php endforeach; ?>
                            </div>
                        </li>
                    <?php else : ?>
                        <li class="nav-item">
                            <a class="nav-link" href="<?= $this->_router->get($menuItem['url']) ?>">
                                <?= $menuItem['title'] ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</nav>
<div id="header-height-fix"></div>