<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>VMS</title>

    <?php $this->getCss(); ?>
</head>

<body>
    <?php $this->getHeader(); ?>
    <div class="container view-wrapper">
        <?php $this->getJs(); ?>
        <?php $this->getContent(); ?>
    </div>
    <?php $this->getFooter(); ?>
</body>

</html>